const tintColorLight = "#4A90E2";
const tintColorDark = "#6AADFF";

export default {
  light: {
    text: "#333333",
    background: "#FFFFFF",
    tint: tintColorLight,
    tabIconDefault: "#CCCCCC",
    tabIconSelected: tintColorLight,
    card: "#F8F9FA",
    border: "#E5E5E5",
    notification: "#FF3B30",
    primary: "#4A90E2",
    secondary: "#5AC8FA",
    success: "#34C759",
    warning: "#FFCC00",
    danger: "#FF3B30",
    muted: "#8E8E93",
    highlight: "#E8F4FF",
    water: "#5AC8FA",
    food: "#FFCC00",
    exercise: "#FF9500",
    premium: "#AF52DE",
  },
  dark: {
    text: "#FFFFFF",
    background: "#121212",
    tint: tintColorDark,
    tabIconDefault: "#6E6E6E",
    tabIconSelected: tintColorDark,
    card: "#1E1E1E",
    border: "#2C2C2C",
    notification: "#FF453A",
    primary: "#6AADFF",
    secondary: "#64D2FF",
    success: "#30D158",
    warning: "#FFD60A",
    danger: "#FF453A",
    muted: "#8E8E93",
    highlight: "#1C3D5A",
    water: "#64D2FF",
    food: "#FFD60A",
    exercise: "#FF9F0A",
    premium: "#BF5AF2",
  },
};